/**
 * Hand-maintained type definitions for @dukelib/sheets.
 *
 * Re-exports everything from generated.d.ts (auto-generated by napi build)
 * and adds manual types for JS-side classes (RowIterator, iterateRows).
 */
export * from './generated'

import type { JsRow, JsRowsOptions, Worksheet as _Worksheet } from './generated'

/** Iterator over sparse rows. Batches FFI calls internally for performance. */
export declare class RowIterator implements IterableIterator<JsRow> {
  [Symbol.iterator](): IterableIterator<JsRow>
  next(): IteratorResult<JsRow>
}

export interface JsPivotMeasureOptions {
  field: string
  aggregate?: 'sum' | 'count' | 'countNumbers' | 'average' | 'max' | 'min' | 'product' | 'stdDev' | 'stdDevP' | 'var' | 'varP'
  name?: string
  showAs?: 'normal' | 'percentOfGrandTotal' | 'percentOfRowTotal' | 'percentOfColumnTotal'
}

export interface JsPivotItemFilterOptions {
  field: string
  items: string[]
}

export interface JsPivotGroupingOptions {
  field: string
  kind: 'number' | 'numeric' | 'date'
  start?: number
  end?: number
  interval?: number
  units?: Array<'seconds' | 'minutes' | 'hours' | 'days' | 'months' | 'quarters' | 'years'>
}

export interface JsPivotTableOptions {
  name: string
  sourceRange?: string
  sourceSheet?: string
  tableName?: string
  target: string
  rows?: string[]
  columns?: string[]
  pages?: string[]
  measures: JsPivotMeasureOptions[]
  filters?: JsPivotItemFilterOptions[]
  groupings?: JsPivotGroupingOptions[]
}

export interface JsPivotRefreshStats {
  pivotCount: number
  pivotsRefreshed: number
  sourceRows: number
  outputCells: number
  cacheHits: number
  cacheMisses: number
}

// Augment the generated Worksheet class with JS-side methods
declare module './generated' {
  interface Workbook {
    /** Refresh all pivot tables in the workbook. */
    refreshPivots(): JsPivotRefreshStats
  }

  interface Worksheet {
    /**
     * Iterate over all rows with data as sparse rows.
     * Only non-empty cells are included. Internally batches FFI calls for performance.
     * When metadata flags are enabled, cells with that metadata are included even if empty.
     */
    iterateRows(opts?: JsRowsOptions): RowIterator

    /** Number of pivot tables on the worksheet. */
    readonly pivotCount: number

    /** Pivot table names on the worksheet. */
    readonly pivotTableNames: string[]

    /** Add a semantic pivot table definition to the worksheet. */
    addPivotTable(options: JsPivotTableOptions): void
  }
}

export interface JsChartExOffset {
  top?: number
  left?: number
}

export interface JsChartExText {
  formula?: string
  value?: string
}

export interface JsChartExColorPosition {
  positionType: string
  value?: number
}

export interface JsChartExValueColorPositions {
  count?: number
  min?: JsChartExColorPosition
  mid?: JsChartExColorPosition
  max?: JsChartExColorPosition
}

export interface JsChartExScaling {
  scalingType: string
  gapWidth?: number
  min?: number
  max?: number
  majorUnit?: number
  minorUnit?: number
}

export interface JsChartExAxisTitle {
  text?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExAxisUnits {
  unit?: string
}

export interface JsChartExSeriesVisibility {
  connectorLines?: boolean
  meanLine?: boolean
  meanMarker?: boolean
  nonoutliers?: boolean
  outliers?: boolean
}

export interface JsChartExBinning {
  intervalClosed?: string
  underflow?: string
  overflow?: string
  binSize?: number
  binCount?: number
}

export interface JsChartExGeography {
  projectionType?: string
  viewedRegionType?: string
  cultureLanguage?: string
  cultureRegion?: string
  attribution?: string
}

export interface JsChartExStatistics {
  quartileMethod?: string
}

export interface JsChartExDataPoint {
  idx: number
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExDataLabel {
  idx: number
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  separator?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExFormatOverride {
  idx: number
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExHeaderFooter {
  alignWithMargins?: boolean
  differentOddEven?: boolean
  differentFirst?: boolean
  oddHeader?: string
  oddFooter?: string
  evenHeader?: string
  evenFooter?: string
  firstHeader?: string
  firstFooter?: string
}

export interface JsChartExPageMargins {
  left?: number
  right?: number
  top?: number
  bottom?: number
  header?: number
  footer?: number
}

export interface JsChartExPageSetup {
  paperSize?: number
  firstPageNumber?: number
  orientation?: string
  blackAndWhite?: boolean
  draft?: boolean
  useFirstPageNumber?: boolean
  horizontalDpi?: number
  verticalDpi?: number
  copies?: number
}

export interface JsChartExPrintSettings {
  headerFooter?: JsChartExHeaderFooter
  pageMargins?: JsChartExPageMargins
  pageSetup?: JsChartExPageSetup
}

export interface JsChartExDimension {
  dimType: string
  formula?: string
  nfFormula?: string
}

export interface JsChartExData {
  id: number
  dimensions: JsChartExDimension[]
}

export interface JsChartExDataLabels {
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  separator?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
  overrides: JsChartExDataLabel[]
  hiddenLabels: number[]
}

export interface JsChartExTitle {
  text?: string
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExLegend {
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExLayoutPr {
  parentLabelLayout?: string
  regionLabelLayout?: string
  visibility?: JsChartExSeriesVisibility
  aggregation: boolean
  binning?: JsChartExBinning
  geography?: JsChartExGeography
  statistics?: JsChartExStatistics
  subtotals: number[]
}

export interface JsChartExAxis {
  id: number
  hidden?: boolean
  scaling: JsChartExScaling
  title?: JsChartExAxisTitle
  units?: JsChartExAxisUnits
  majorGridlines?: import('./generated').JsChartShapeProperties
  minorGridlines?: import('./generated').JsChartShapeProperties
  majorTickMarks?: string
  minorTickMarks?: string
  tickLabels: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExPlotArea {
  plotSurface?: import('./generated').JsChartShapeProperties
  series: JsChartExSeries[]
  axes: JsChartExAxis[]
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExSeries {
  layout: string
  dataId: number
  uniqueId?: string
  hidden?: boolean
  ownerIdx?: number
  formatIdx?: number
  text?: JsChartExText
  dataLabels?: JsChartExDataLabels
  dataPoints: JsChartExDataPoint[]
  layoutProperties?: JsChartExLayoutPr
  axisIds: number[]
  valueColors: boolean
  valueColorPositions?: JsChartExValueColorPositions
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartEx {
  layout: string
  version?: string
  featureList?: string
  fallbackImg?: string
  title?: JsChartExTitle
  data: JsChartExData[]
  plotArea: JsChartExPlotArea
  legend?: JsChartExLegend
  anchor: import('./generated').JsChartAnchor
  shapeProperties?: import('./generated').JsChartShapeProperties
  formatOverrides: JsChartExFormatOverride[]
  printSettings?: JsChartExPrintSettings
}
