/**
 * Hand-maintained type definitions for @dukelib/sheets.
 *
 * Re-exports everything from generated.d.ts (auto-generated by napi build)
 * and adds manual types for JS-side classes and recursive drawing DTOs.
 */
export * from './generated'

import type * as Generated from './generated'
import type { JsRow, JsRowsOptions } from './generated'

/** Iterator over sparse rows. Batches FFI calls internally for performance. */
export declare class RowIterator implements IterableIterator<JsRow> {
  [Symbol.iterator](): IterableIterator<JsRow>
  next(): IteratorResult<JsRow>
}

export interface JsChartExOffset {
  top?: number
  left?: number
}

export interface JsChartExText {
  formula?: string
  value?: string
}

export interface JsChartExColorPosition {
  positionType: string
  value?: number
}

export interface JsChartExValueColorPositions {
  count?: number
  min?: JsChartExColorPosition
  mid?: JsChartExColorPosition
  max?: JsChartExColorPosition
}

export interface JsChartExScaling {
  scalingType: string
  gapWidth?: number
  min?: number
  max?: number
  majorUnit?: number
  minorUnit?: number
}

export interface JsChartExAxisTitle {
  text?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExAxisUnits {
  unit?: string
}

export interface JsChartExSeriesVisibility {
  connectorLines?: boolean
  meanLine?: boolean
  meanMarker?: boolean
  nonoutliers?: boolean
  outliers?: boolean
}

export interface JsChartExBinning {
  intervalClosed?: string
  underflow?: string
  overflow?: string
  binSize?: number
  binCount?: number
}

export interface JsChartExGeography {
  projectionType?: string
  viewedRegionType?: string
  cultureLanguage?: string
  cultureRegion?: string
  attribution?: string
}

export interface JsChartExStatistics {
  quartileMethod?: string
}

export interface JsChartExDataPoint {
  idx: number
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExDataLabel {
  idx: number
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  separator?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExFormatOverride {
  idx: number
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExHeaderFooter {
  alignWithMargins?: boolean
  differentOddEven?: boolean
  differentFirst?: boolean
  oddHeader?: string
  oddFooter?: string
  evenHeader?: string
  evenFooter?: string
  firstHeader?: string
  firstFooter?: string
}

export interface JsChartExPageMargins {
  left?: number
  right?: number
  top?: number
  bottom?: number
  header?: number
  footer?: number
}

export interface JsChartExPageSetup {
  paperSize?: number
  firstPageNumber?: number
  orientation?: string
  blackAndWhite?: boolean
  draft?: boolean
  useFirstPageNumber?: boolean
  horizontalDpi?: number
  verticalDpi?: number
  copies?: number
}

export interface JsChartExPrintSettings {
  headerFooter?: JsChartExHeaderFooter
  pageMargins?: JsChartExPageMargins
  pageSetup?: JsChartExPageSetup
}

export interface JsChartExDimension {
  dimType: string
  formula?: string
  nfFormula?: string
}

export interface JsChartExData {
  id: number
  dimensions: JsChartExDimension[]
}

export interface JsChartExDataLabels {
  position?: string
  visibilitySeriesName?: boolean
  visibilityCategoryName?: boolean
  visibilityValue?: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  separator?: string
  shapeProperties?: import('./generated').JsChartShapeProperties
  overrides: JsChartExDataLabel[]
  hiddenLabels: number[]
}

export interface JsChartExTitle {
  text?: string
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExLegend {
  position?: string
  align?: string
  overlay?: boolean
  offset?: JsChartExOffset
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExLayoutPr {
  parentLabelLayout?: string
  regionLabelLayout?: string
  visibility?: JsChartExSeriesVisibility
  aggregation: boolean
  binning?: JsChartExBinning
  geography?: JsChartExGeography
  statistics?: JsChartExStatistics
  subtotals: number[]
}

export interface JsChartExAxis {
  id: number
  hidden?: boolean
  scaling: JsChartExScaling
  title?: JsChartExAxisTitle
  units?: JsChartExAxisUnits
  majorGridlines?: import('./generated').JsChartShapeProperties
  minorGridlines?: import('./generated').JsChartShapeProperties
  majorTickMarks?: string
  minorTickMarks?: string
  tickLabels: boolean
  numberFormat?: import('./generated').JsChartNumberFormat
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExPlotArea {
  plotSurface?: import('./generated').JsChartShapeProperties
  series: JsChartExSeries[]
  axes: JsChartExAxis[]
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartExSeries {
  layout: string
  dataId: number
  uniqueId?: string
  hidden?: boolean
  ownerIdx?: number
  formatIdx?: number
  text?: JsChartExText
  dataLabels?: JsChartExDataLabels
  dataPoints: JsChartExDataPoint[]
  layoutProperties?: JsChartExLayoutPr
  axisIds: number[]
  valueColors: boolean
  valueColorPositions?: JsChartExValueColorPositions
  shapeProperties?: import('./generated').JsChartShapeProperties
}

export interface JsChartEx {
  layout: string
  version?: string
  featureList?: string
  fallbackImg?: string
  title?: JsChartExTitle
  data: JsChartExData[]
  plotArea: JsChartExPlotArea
  legend?: JsChartExLegend
  shapeProperties?: import('./generated').JsChartShapeProperties
  formatOverrides: JsChartExFormatOverride[]
  printSettings?: JsChartExPrintSettings
  externalDataRelId?: string
  externalDataAutoUpdate?: boolean
}

export type JsChart = Omit<Generated.JsChart, 'anchor'>
export type JsChartSheet = Omit<Generated.JsChartSheet, 'chart'> & { chart: JsChart }

export interface DrawingMeta {
  name?: string
  hidden: boolean
  locked: boolean
  printable: boolean
  altText?: string
  title?: string
}

export interface DrawingMetaInput {
  name?: string
  hidden?: boolean
  locked?: boolean
  printable?: boolean
  altText?: string
  title?: string
}

/** Flat two-cell anchor used by the existing Node.js chart/drawing API. */
export type DrawingAnchor = Generated.JsDrawingAnchor

export interface DrawingChildTransform {
  xEmu?: number
  yEmu?: number
  cxEmu?: number
  cyEmu?: number
  rotation?: number
  flipH?: boolean
  flipV?: boolean
}

export interface DrawingGroupTransform extends DrawingChildTransform {
  childXEmu?: number
  childYEmu?: number
  childCxEmu?: number
  childCyEmu?: number
}

export type DrawingPlacement =
  | { anchor: DrawingAnchor; transform?: never }
  | { anchor?: never; transform: DrawingChildTransform }

export type DrawingColor =
  | { colorType: 'auto' }
  | { colorType: 'rgb'; r: number; g: number; b: number }
  | { colorType: 'argb'; a: number; r: number; g: number; b: number }
  | { colorType: 'theme'; index: number; tint: number }
  | { colorType: 'indexed'; index: number }

export interface DrawingRunFont {
  bold?: boolean
  italic?: boolean
  size?: number
  color?: DrawingColor
  name?: string
  underline?: 'none' | 'single' | 'double' | 'singleAccounting' | 'doubleAccounting'
  strikethrough?: boolean
  verticalAlign?: 'baseline' | 'superscript' | 'subscript'
  family?: number
  charset?: number
  scheme?: string
}

export interface DrawingText {
  runs: Array<{ text: string; font?: DrawingRunFont }>
  horizontalAlignment?: 'general' | 'left' | 'center' | 'right' | 'fill' | 'justify' | 'centerContinuous' | 'distributed'
  verticalAlignment?: 'top' | 'center' | 'bottom' | 'justify' | 'distributed'
}

export type FormControlKind =
  | { kind: 'button'; caption: DrawingText }
  | { kind: 'checkbox'; caption: DrawingText; state: 'unchecked' | 'checked' | 'mixed'; cellLink?: string; no3D: boolean }
  | { kind: 'optionButton'; caption: DrawingText; state: 'unchecked' | 'checked'; cellLink?: string; firstInGroup: boolean; no3D: boolean }
  | { kind: 'label'; caption: DrawingText }
  | { kind: 'groupBox'; caption: DrawingText; no3D: boolean }
  | { kind: 'listBox'; inputRange?: string; cellLink?: string; selection: 'single' | 'multi' | 'extend'; selected: number[]; no3D: boolean }
  | { kind: 'dropdown'; inputRange?: string; cellLink?: string; selected?: number; lines: number; no3D: boolean }
  | { kind: 'scrollbar'; value: number; min: number; max: number; increment: number; page: number; horizontal: boolean; cellLink?: string }
  | { kind: 'spinner'; value: number; min: number; max: number; increment: number; cellLink?: string }
  | { kind: 'unknown'; objectType: string; legacyObjectType?: number; caption: DrawingText }

export type FormControlKindInput =
  | { kind: 'button'; caption: DrawingText }
  | { kind: 'checkbox'; caption: DrawingText; state: 'unchecked' | 'checked' | 'mixed'; cellLink?: string; no3D?: boolean }
  | { kind: 'optionButton'; caption: DrawingText; state: 'unchecked' | 'checked'; cellLink?: string; firstInGroup?: boolean; no3D?: boolean }
  | { kind: 'label'; caption: DrawingText }
  | { kind: 'groupBox'; caption: DrawingText; no3D?: boolean }
  | { kind: 'listBox'; inputRange?: string; cellLink?: string; selection: 'single' | 'multi' | 'extend'; selected?: number[]; no3D?: boolean }
  | { kind: 'dropdown'; inputRange?: string; cellLink?: string; selected?: number; lines: number; no3D?: boolean }
  | { kind: 'scrollbar'; value: number; min: number; max: number; increment: number; page: number; horizontal?: boolean; cellLink?: string }
  | { kind: 'spinner'; value: number; min: number; max: number; increment: number; cellLink?: string }
  | { kind: 'unknown'; objectType: string; legacyObjectType?: number; caption?: DrawingText }

export interface FormControlPayload {
  kind: FormControlKind
  macroName?: string
}

export interface FormControlInputPayload {
  kind: FormControlKindInput
  macroName?: string
}

export interface DrawingImage {
  format: 'png' | 'jpeg' | 'gif' | 'bmp' | 'emf' | 'wmf' | 'tiff' | 'svg'
  mediaPath: string
  svgMediaPath?: string
  widthEmu: number
  heightEmu: number
  rotation?: number
  flipH: boolean
  flipV: boolean
}

export interface DrawingImageInput extends Partial<Omit<DrawingImage, 'format' | 'widthEmu' | 'heightEmu'>> {
  format: DrawingImage['format']
  widthEmu: number
  heightEmu: number
  data: Buffer
  svgData?: Buffer
}

export type DrawingShapeFill =
  | { kind: 'none' }
  | { kind: 'solid'; color: DrawingColor }

export interface DrawingShape {
  geometry: string
  fill: DrawingShapeFill
  line: { color?: DrawingColor; widthEmu?: number; dashStyle?: string; noFill: boolean }
  text?: DrawingText
  rotation: number
  flipH: boolean
  flipV: boolean
}

export interface DrawingShapeInput extends Partial<DrawingShape> {
  geometry?: string
}

export interface DrawingComment {
  row: number
  col: number
  author: string
  text: string
}

export type ChartDataReferenceInput =
  | { refType: 'formula'; formula: string }
  | { refType: 'numbers'; numbers: number[] }
  | { refType: 'strings'; strings: string[] }

export interface ChartSeriesInput {
  name?: string
  values: ChartDataReferenceInput
  categories?: ChartDataReferenceInput
}

export type ChartInput = Partial<Omit<JsChart, 'chartType' | 'series'>> & {
  chartType: string
  series?: ChartSeriesInput[]
}

export type ChartExInput = Partial<JsChartEx> & { layout: string }

export interface RawDrawingMetadata {
  byteLength: number
  relationshipCount: number
}

type DrawingNode = DrawingMeta & DrawingPlacement & { drawingPath: number[] }

export type DrawnImage = DrawingNode & { kind: 'image'; image: DrawingImage }
export type DrawnChart = DrawingNode & { kind: 'chart'; chart: JsChart }
export type DrawnChartEx = DrawingNode & { kind: 'chartEx'; chartEx: JsChartEx }
export type DrawnFormControl = DrawingNode & { kind: 'formControl'; formControl: FormControlPayload }
export type DrawnComment = DrawingNode & { kind: 'comment'; comment: DrawingComment }
export type DrawnShape = DrawingNode & { kind: 'shape'; shape: DrawingShape }
export type DrawnGroup = DrawingNode & { kind: 'group'; group: { groupTransform: DrawingGroupTransform; children: Drawing[] } }
export type DrawnRaw = DrawingNode & { kind: 'raw'; raw: RawDrawingMetadata }

export type Drawing = DrawnImage | DrawnChart | DrawnChartEx | DrawnFormControl | DrawnComment | DrawnShape | DrawnGroup | DrawnRaw

type DrawingInputPayload =
  | { kind: 'image'; image: DrawingImageInput }
  | { kind: 'chart'; chart: ChartInput }
  | { kind: 'chartEx'; chartEx: ChartExInput }
  | { kind: 'formControl'; formControl: FormControlInputPayload }
  | { kind: 'comment'; comment: DrawingComment }
  | { kind: 'shape'; shape: DrawingShapeInput }
  | { kind: 'group'; group: { groupTransform?: DrawingGroupTransform; children?: DrawingInput[] } }

export type TopLevelDrawingInput = DrawingMetaInput & {
  anchor: DrawingAnchor
  transform?: never
} & DrawingInputPayload

export type GroupChildDrawingInput = DrawingMetaInput & {
  anchor?: never
  transform: DrawingChildTransform
} & DrawingInputPayload

export type DrawingInput = TopLevelDrawingInput | GroupChildDrawingInput

export interface FormControlInteractionResult {
  controlsChanged: number
  linkedCellsChanged: number
}

type ReplacedWorksheetMembers =
  | 'drawings'
  | 'charts'
  | 'chartCount'
  | 'chartsEx'
  | 'chartExCount'
  | 'images'
  | 'imageCount'
  | 'formControls'
  | 'formControlCount'
  | 'addFormControl'
  | 'setFormControl'
  | 'removeFormControl'
  | 'addDrawing'
  | 'insertDrawing'
  | 'setDrawing'
  | 'removeDrawing'
  | 'moveDrawing'
  | 'drawingImageData'
  | 'drawingSvgData'
  | 'setFormControlCheckState'

export type Worksheet = Omit<Generated.Worksheet, ReplacedWorksheetMembers> & {
  /** Iterate over sparse rows, batching native calls internally. */
  iterateRows(opts?: JsRowsOptions): RowIterator
  readonly drawings: Drawing[]
  readonly formControls: DrawnFormControl[]
  readonly formControlCount: number
  readonly images: DrawnImage[]
  readonly imageCount: number
  readonly charts: DrawnChart[]
  readonly chartCount: number
  readonly chartsEx: DrawnChartEx[]
  readonly chartExCount: number
  addDrawing(input: TopLevelDrawingInput): number
  insertDrawing(index: number, input: TopLevelDrawingInput): void
  setDrawing(path: number[], input: DrawingInput): void
  removeDrawing(path: number[]): void
  moveDrawing(from: number, to: number): void
  drawingImageData(path: number[]): Buffer
  drawingSvgData(path: number[]): Buffer | null
  setFormControlCheckState(path: number[], state: Generated.JsCheckState): FormControlInteractionResult
}

export declare const Worksheet: {
  readonly prototype: Worksheet
}

export type Workbook = Omit<
  Generated.Workbook,
  'getSheet' | 'chartsheets' | 'syncFormControls' | 'syncFormControlsFromLinkedCells'
> & {
  getSheet(indexOrName: number | string): Worksheet
  readonly chartsheets: JsChartSheet[]
  syncFormControls(): number
  syncFormControlsFromLinkedCells(): number
}

export declare const Workbook: {
  readonly prototype: Workbook
  new (): Workbook
  open(path: string): Workbook
  fromBytes(data: Buffer): Workbook
  fromCsvString(csv: string): Workbook
  openWithPassword(path: string, password: string, skipIntegrityCheck?: boolean | null): Workbook
}

export declare function openAsync(path: string): Promise<Workbook>
export declare function fromBytesAsync(data: Buffer): Promise<Workbook>
