//! End-to-end test: decrypt the LibreOffice-generated XLS RC4 CryptoAPI
//! fixture and assert the known cell values.
//!
//! The fixture is generated by `mise run crypto:fixtures` (which runs the
//! `fixture_gen.rs` test in the crypto crate). The fixture directory is
//! gitignored; this test is gated behind `#[ignore]` and skips with a
//! helpful message if the fixture is absent.

use std::path::PathBuf;

use duke_sheets_xls::{XlsError, XlsReader};

fn fixture(name: &str) -> Option<PathBuf> {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("..");
    p.push("duke-sheets-crypto");
    p.push("tests/fixtures");
    p.push(name);
    p.canonicalize().ok()
}

/// Password the fixture generator writes. Mirrors
/// `FIXTURE_PASSWORD` in `duke-sheets-crypto/tests/fixture_gen.rs`.
const FIXTURE_PASSWORD: &str = "duke-test-pw";

#[test]
fn encrypted_xls_fails_without_password() {
    let Some(path) = fixture("xls_rc4_cryptoapi.xls") else {
        eprintln!("SKIP: xls_rc4_cryptoapi.xls fixture not found; run `mise run crypto:fixtures`");
        return;
    };
    let err = XlsReader::read_file(&path).expect_err("must be encrypted");
    match err {
        XlsError::Encrypted(msg) => {
            assert!(msg.contains("RC4"), "unexpected Encrypted msg: {msg}");
        }
        other => panic!("expected XlsError::Encrypted, got {other:?}"),
    }
}

#[test]
fn encrypted_xls_decrypts_with_correct_password() {
    let Some(path) = fixture("xls_rc4_cryptoapi.xls") else {
        eprintln!("SKIP: xls_rc4_cryptoapi.xls fixture not found; run `mise run crypto:fixtures`");
        return;
    };
    let workbook = XlsReader::read_file_with_password(&path, Some(FIXTURE_PASSWORD))
        .expect("decryption with correct password must succeed");

    let sheet = workbook.worksheet(0).expect("sheet 0");
    // The fixture is built with A1="hello crypto", B1=42.0.
    // Use raw address lookups since we want to verify decrypted content
    // round-trips through the normal XLS reader unchanged.
    let a1 = sheet.get_value("A1").expect("A1 must be a string");
    let b1 = sheet.get_value("B1").expect("B1 must be a number");

    assert_eq!(a1.as_string().as_deref(), Some("hello crypto"), "A1 value");
    assert_eq!(b1.as_number(), Some(42.0), "B1 value");
}

#[test]
fn encrypted_xls_wrong_password_yields_bad_password() {
    let Some(path) = fixture("xls_rc4_cryptoapi.xls") else {
        eprintln!("SKIP: xls_rc4_cryptoapi.xls fixture not found; run `mise run crypto:fixtures`");
        return;
    };
    let err = XlsReader::read_file_with_password(&path, Some("wrong-password"))
        .expect_err("must reject wrong password");
    assert!(
        matches!(err, XlsError::BadPassword),
        "expected BadPassword, got {err:?}"
    );
}

#[test]
fn plain_xls_password_ignored() {
    let Some(path) = fixture("xls_rc4_cryptoapi.plain.xls") else {
        eprintln!("SKIP: plain fixture not found");
        return;
    };
    // Supplying a password on a non-encrypted file should just work.
    let workbook = XlsReader::read_file_with_password(&path, Some("anything"))
        .expect("plain file should open regardless of password arg");
    assert!(workbook.sheet_count() >= 1);
}
