//! Round-trip tests for embedded PNG images in XLS.
//!
//! Exercises the in-process loop: build a workbook with an
//! `EmbeddedImage`, write to BIFF8 bytes, read back, assert the
//! image survives with its anchor + format + raw payload bytes
//! intact.

use std::io::Cursor;

use duke_sheets_chart::{CellMarker, DrawingAnchor, EditAs, EmbeddedImage, ImageFormat};
use duke_sheets_core::Workbook;
use duke_sheets_xls::{XlsReader, XlsWriter};

/// A 68-byte 1x1 transparent PNG with verified chunk CRCs, used as
/// the deterministic image payload for these tests.
const TEST_PNG_1X1: &[u8] = &[
    0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1F, 0x15, 0xC4,
    0x89, 0x00, 0x00, 0x00, 0x0B, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9C, 0x63, 0x60, 0x00, 0x02, 0x00,
    0x00, 0x05, 0x00, 0x01, 0x7A, 0x5E, 0xAB, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44,
    0xAE, 0x42, 0x60, 0x82,
];

fn write_then_read(wb: &Workbook) -> Workbook {
    let bytes = XlsWriter::write_to_bytes(wb).expect("serialize");
    XlsReader::read(Cursor::new(&bytes)).expect("read back")
}

fn test_image(id: u32, name: &str, from_col: u16, from_row: u32) -> EmbeddedImage {
    test_image_with_format(id, name, from_col, from_row, ImageFormat::Png, TEST_PNG_1X1)
}

fn test_image_with_format(
    id: u32,
    name: &str,
    from_col: u16,
    from_row: u32,
    format: ImageFormat,
    data: &[u8],
) -> EmbeddedImage {
    EmbeddedImage {
        id,
        name: name.to_string(),
        description: None,
        anchor: DrawingAnchor::TwoCell {
            from: CellMarker {
                col: from_col,
                col_offset_emu: 0,
                row: from_row,
                row_offset_emu: 0,
            },
            to: CellMarker {
                col: from_col + 3,
                col_offset_emu: 0,
                row: from_row + 5,
                row_offset_emu: 0,
            },
            edit_as: None,
        },
        format,
        media_path: String::new(),
        svg_media_path: None,
        width_emu: 1_000_000,
        height_emu: 1_000_000,
        rotation: None,
        flip_h: false,
        flip_v: false,
        data: data.to_vec(),
        svg_data: None,
    }
}

/// 632-byte 1x1 RGB JPEG at quality 50, generated by Python's PIL.
/// Valid enough for Excel and other decoders to retain on re-save
/// (a smaller cooked-up JPEG was silently dropped by Excel during
/// the SaveAs round-trip).
const TEST_JPEG_1X1: &[u8] = &[
    0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01,
    0x00, 0x01, 0x00, 0x00, 0xFF, 0xDB, 0x00, 0x43, 0x00, 0x10, 0x0B, 0x0C, 0x0E, 0x0C, 0x0A, 0x10,
    0x0E, 0x0D, 0x0E, 0x12, 0x11, 0x10, 0x13, 0x18, 0x28, 0x1A, 0x18, 0x16, 0x16, 0x18, 0x31, 0x23,
    0x25, 0x1D, 0x28, 0x3A, 0x33, 0x3D, 0x3C, 0x39, 0x33, 0x38, 0x37, 0x40, 0x48, 0x5C, 0x4E, 0x40,
    0x44, 0x57, 0x45, 0x37, 0x38, 0x50, 0x6D, 0x51, 0x57, 0x5F, 0x62, 0x67, 0x68, 0x67, 0x3E, 0x4D,
    0x71, 0x79, 0x70, 0x64, 0x78, 0x5C, 0x65, 0x67, 0x63, 0xFF, 0xDB, 0x00, 0x43, 0x01, 0x11, 0x12,
    0x12, 0x18, 0x15, 0x18, 0x2F, 0x1A, 0x1A, 0x2F, 0x63, 0x42, 0x38, 0x42, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63,
    0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0x63, 0xFF, 0xC0,
    0x00, 0x11, 0x08, 0x00, 0x01, 0x00, 0x01, 0x03, 0x01, 0x22, 0x00, 0x02, 0x11, 0x01, 0x03, 0x11,
    0x01, 0xFF, 0xC4, 0x00, 0x1F, 0x00, 0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09,
    0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x10, 0x00, 0x02, 0x01, 0x03, 0x03, 0x02, 0x04, 0x03, 0x05,
    0x05, 0x04, 0x04, 0x00, 0x00, 0x01, 0x7D, 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21,
    0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14, 0x32, 0x81, 0x91, 0xA1, 0x08, 0x23,
    0x42, 0xB1, 0xC1, 0x15, 0x52, 0xD1, 0xF0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0A, 0x16, 0x17,
    0x18, 0x19, 0x1A, 0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A,
    0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A,
    0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A,
    0x83, 0x84, 0x85, 0x86, 0x87, 0x88, 0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99,
    0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7,
    0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4, 0xD5,
    0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2, 0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF1,
    0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFF, 0xC4, 0x00, 0x1F, 0x01, 0x00, 0x03,
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x11, 0x00,
    0x02, 0x01, 0x02, 0x04, 0x04, 0x03, 0x04, 0x07, 0x05, 0x04, 0x04, 0x00, 0x01, 0x02, 0x77, 0x00,
    0x01, 0x02, 0x03, 0x11, 0x04, 0x05, 0x21, 0x31, 0x06, 0x12, 0x41, 0x51, 0x07, 0x61, 0x71, 0x13,
    0x22, 0x32, 0x81, 0x08, 0x14, 0x42, 0x91, 0xA1, 0xB1, 0xC1, 0x09, 0x23, 0x33, 0x52, 0xF0, 0x15,
    0x62, 0x72, 0xD1, 0x0A, 0x16, 0x24, 0x34, 0xE1, 0x25, 0xF1, 0x17, 0x18, 0x19, 0x1A, 0x26, 0x27,
    0x28, 0x29, 0x2A, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49,
    0x4A, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69,
    0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x82, 0x83, 0x84, 0x85, 0x86, 0x87, 0x88,
    0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6,
    0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5, 0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4,
    0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE2,
    0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9,
    0xFA, 0xFF, 0xDA, 0x00, 0x0C, 0x03, 0x01, 0x00, 0x02, 0x11, 0x03, 0x11, 0x00, 0x3F, 0x00, 0xC5,
    0xA2, 0x8A, 0x2B, 0xCB, 0x3E, 0xF0, 0xFF, 0xD9,
];

#[test]
fn single_picture_round_trips() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_image(test_image(1, "Picture 1", 2, 3));

    let parsed = write_then_read(&wb);
    let images = parsed.worksheet(0).unwrap().images();
    assert_eq!(images.len(), 1, "picture must survive round-trip");

    let img = &images[0];
    assert_eq!(img.format, ImageFormat::Png);
    assert_eq!(img.data, TEST_PNG_1X1, "PNG bytes must round-trip verbatim");
    assert_eq!(img.name, "Picture 1");
    if let DrawingAnchor::TwoCell { from, to, .. } = &img.anchor {
        assert_eq!(from.col, 2);
        assert_eq!(from.row, 3);
        assert_eq!(to.col, 5);
        assert_eq!(to.row, 8);
    } else {
        panic!("expected TwoCell anchor, got {:?}", img.anchor);
    }
}

#[test]
fn twocell_anchor_edit_as_round_trips() {
    // editAs=TwoCell (or None) maps to ClientAnchor flag=0
    // (move+resize with cells). Round-trip should preserve the
    // editAs setting as TwoCell since the reader maps flag=0 →
    // TwoCell.
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut img = test_image(1, "Picture 1", 1, 2);
    img.anchor = DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 1,
            col_offset_emu: 0,
            row: 2,
            row_offset_emu: 0,
        },
        to: CellMarker {
            col: 4,
            col_offset_emu: 0,
            row: 7,
            row_offset_emu: 0,
        },
        edit_as: Some(EditAs::TwoCell),
    };
    ws.add_image(img);

    let parsed = write_then_read(&wb);
    let img = &parsed.worksheet(0).unwrap().images()[0];
    if let DrawingAnchor::TwoCell { edit_as, .. } = &img.anchor {
        assert_eq!(*edit_as, Some(EditAs::TwoCell));
    } else {
        panic!("expected TwoCell");
    }
}

#[test]
fn onecell_anchor_round_trips_with_visual_area_preserved() {
    // OneCell input: from cell + width/height in EMU.
    // Writer encodes this as a TwoCell-style ClientAnchor with
    // flag=2 (move only). Reader maps flag=2 back to TwoCell with
    // editAs=OneCell. The variant tag is lost but the visual area
    // is preserved.
    const COL_EMU: i64 = 609_600;
    const ROW_EMU: i64 = 190_500;
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut img = test_image(1, "Picture 1", 0, 0);
    img.anchor = DrawingAnchor::OneCell {
        from: CellMarker {
            col: 2,
            col_offset_emu: 0,
            row: 3,
            row_offset_emu: 0,
        },
        // Exactly 3 columns × 2 rows worth of default cells.
        width_emu: 3 * COL_EMU,
        height_emu: 2 * ROW_EMU,
    };
    ws.add_image(img);

    let parsed = write_then_read(&wb);
    let img = &parsed.worksheet(0).unwrap().images()[0];
    match &img.anchor {
        DrawingAnchor::TwoCell {
            from,
            to,
            edit_as,
        } => {
            assert_eq!(from.col, 2);
            assert_eq!(from.row, 3);
            assert_eq!(to.col, 5, "OneCell width must extend by 3 cols");
            assert_eq!(to.row, 5, "OneCell height must extend by 2 rows");
            assert_eq!(*edit_as, Some(EditAs::OneCell));
        }
        other => panic!("expected TwoCell with editAs=OneCell, got {other:?}"),
    }
    assert_eq!(img.width_emu, 3 * COL_EMU);
    assert_eq!(img.height_emu, 2 * ROW_EMU);
}

#[test]
fn absolute_anchor_round_trips_with_visual_area_preserved() {
    // Absolute input: explicit x/y position + width/height in EMU.
    // Writer encodes this as a TwoCell-style ClientAnchor with
    // flag=3 (no move, no resize). Reader maps flag=3 back to
    // TwoCell with editAs=Absolute.
    const COL_EMU: i64 = 609_600;
    const ROW_EMU: i64 = 190_500;
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut img = test_image(1, "Picture 1", 0, 0);
    img.anchor = DrawingAnchor::Absolute {
        x_emu: 4 * COL_EMU,
        y_emu: 3 * ROW_EMU,
        width_emu: 2 * COL_EMU,
        height_emu: 4 * ROW_EMU,
    };
    ws.add_image(img);

    let parsed = write_then_read(&wb);
    let img = &parsed.worksheet(0).unwrap().images()[0];
    match &img.anchor {
        DrawingAnchor::TwoCell {
            from,
            to,
            edit_as,
        } => {
            assert_eq!(from.col, 4, "Absolute x must land in col 4");
            assert_eq!(from.row, 3, "Absolute y must land in row 3");
            assert_eq!(to.col, 6, "width extends from col 4 by 2");
            assert_eq!(to.row, 7, "height extends from row 3 by 4");
            assert_eq!(*edit_as, Some(EditAs::Absolute));
        }
        other => panic!("expected TwoCell with editAs=Absolute, got {other:?}"),
    }
}

#[test]
fn picture_anchor_within_cell_offsets_round_trip() {
    // Within-cell EMU offsets quantise to ClientAnchor 1024ths/256ths.
    // Use offsets that are exact multiples of the writer's per-unit
    // constants (595 EMU / dx unit, 744 EMU / dy unit) so the
    // round-trip is exact.
    let dx_unit = 595i64;
    let dy_unit = 744i64;
    let from_col_off = 10 * dx_unit; // 5,950 EMU
    let from_row_off = 4 * dy_unit; // 2,976 EMU
    let to_col_off = 50 * dx_unit; // 29,750 EMU
    let to_row_off = 12 * dy_unit; // 8,928 EMU

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    let mut img = test_image(1, "Picture 1", 1, 2);
    img.anchor = DrawingAnchor::TwoCell {
        from: CellMarker {
            col: 1,
            col_offset_emu: from_col_off,
            row: 2,
            row_offset_emu: from_row_off,
        },
        to: CellMarker {
            col: 4,
            col_offset_emu: to_col_off,
            row: 7,
            row_offset_emu: to_row_off,
        },
        edit_as: None,
    };
    ws.add_image(img);

    let parsed = write_then_read(&wb);
    let images = parsed.worksheet(0).unwrap().images();
    assert_eq!(images.len(), 1);
    if let DrawingAnchor::TwoCell { from, to, .. } = &images[0].anchor {
        assert_eq!(from.col_offset_emu, from_col_off);
        assert_eq!(from.row_offset_emu, from_row_off);
        assert_eq!(to.col_offset_emu, to_col_off);
        assert_eq!(to.row_offset_emu, to_row_off);
    } else {
        panic!("expected TwoCell anchor");
    }

    // Synthesised width/height should reflect the cell span at
    // Excel's default cell sizes plus the within-cell delta.
    let img = &images[0];
    assert!(img.width_emu > 0, "width_emu should be synthesised non-zero");
    assert!(
        img.height_emu > 0,
        "height_emu should be synthesised non-zero"
    );

    // Span: 4-1=3 cols × 609,600 + (to_off - from_off).
    let expected_width = 3 * 609_600 + (to_col_off - from_col_off);
    let expected_height = 5 * 190_500 + (to_row_off - from_row_off);
    assert_eq!(img.width_emu, expected_width);
    assert_eq!(img.height_emu, expected_height);
}

#[test]
fn single_jpeg_picture_round_trips() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", "anchor").expect("A1");
    ws.add_image(test_image_with_format(
        1,
        "JpegPic",
        1,
        2,
        ImageFormat::Jpeg,
        TEST_JPEG_1X1,
    ));

    let parsed = write_then_read(&wb);
    let images = parsed.worksheet(0).unwrap().images();
    assert_eq!(images.len(), 1, "JPEG must round-trip");
    let img = &images[0];
    assert_eq!(img.format, ImageFormat::Jpeg, "format must stay JPEG");
    assert_eq!(
        img.data, TEST_JPEG_1X1,
        "JPEG bytes must round-trip verbatim"
    );
}

#[test]
fn png_and_jpeg_coexist_on_one_sheet() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_image(test_image(1, "PngPic", 0, 0));
    ws.add_image(test_image_with_format(
        2,
        "JpegPic",
        5,
        5,
        ImageFormat::Jpeg,
        TEST_JPEG_1X1,
    ));

    let parsed = write_then_read(&wb);
    let images = parsed.worksheet(0).unwrap().images();
    assert_eq!(images.len(), 2);
    // Map by format since reader order should match writer order.
    assert_eq!(images[0].format, ImageFormat::Png);
    assert_eq!(images[0].data, TEST_PNG_1X1);
    assert_eq!(images[1].format, ImageFormat::Jpeg);
    assert_eq!(images[1].data, TEST_JPEG_1X1);
}

#[test]
fn multiple_pictures_round_trip_on_one_sheet() {
    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_image(test_image(1, "Picture 1", 0, 0));
    ws.add_image(test_image(2, "Picture 2", 4, 4));
    ws.add_image(test_image(3, "Picture 3", 8, 8));

    let parsed = write_then_read(&wb);
    let images = parsed.worksheet(0).unwrap().images();
    assert_eq!(images.len(), 3, "all three pictures must round-trip");
    for img in images {
        assert_eq!(img.format, ImageFormat::Png);
        assert_eq!(
            img.data, TEST_PNG_1X1,
            "each picture's PNG bytes must survive verbatim"
        );
    }
}

#[test]
fn picture_and_comment_coexist_on_same_sheet() {
    use duke_sheets_core::CellComment;

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.add_image(test_image(1, "Picture 1", 1, 1));
    ws.set_comment_at(3, 3, CellComment::new("Alice", "A note"));

    let parsed = write_then_read(&wb);
    let ws_in = parsed.worksheet(0).unwrap();
    assert_eq!(ws_in.image_count(), 1, "picture must survive");
    assert_eq!(ws_in.comment_count(), 1, "comment must survive");
    assert_eq!(ws_in.comment_at(3, 3).unwrap().text, "A note");
    assert_eq!(ws_in.images()[0].name, "Picture 1");
}

#[test]
fn pictures_on_multiple_sheets_round_trip() {
    let mut wb = Workbook::new();
    wb.rename_worksheet(0, "First").expect("rename");
    wb.add_worksheet_with_name("Second").expect("add");

    wb.worksheet_mut(0)
        .unwrap()
        .add_image(test_image(1, "Pic on First", 0, 0));
    wb.worksheet_mut(1)
        .unwrap()
        .add_image(test_image(2, "Pic on Second", 2, 2));

    let parsed = write_then_read(&wb);
    assert_eq!(parsed.worksheet(0).unwrap().image_count(), 1);
    assert_eq!(parsed.worksheet(1).unwrap().image_count(), 1);
    assert_eq!(
        parsed.worksheet(0).unwrap().images()[0].name,
        "Pic on First"
    );
    assert_eq!(
        parsed.worksheet(1).unwrap().images()[0].name,
        "Pic on Second"
    );
}

/// LibreOffice envelope check: write an XLS with one PNG image,
/// push to the LO shared dir, open via URP, read the anchor cell's
/// value back. Catches structural malformations in the Escher tree
/// (Blip/FBSE/BSTORE_CONTAINER + picture SP_CONTAINER) that would
/// make LO refuse the file.
#[test]
#[ignore = "requires LibreOffice URP on 127.0.0.1:2002"]
fn lo_can_open_xls_with_picture_we_emit() {
    duke_sheets_test_harness::lo::ensure_lo();

    const SHARED_DIR: &str = "/tmp/duke-sheets-urp";

    let mut wb = Workbook::new();
    let ws = wb.worksheet_mut(0).unwrap();
    ws.set_cell_value("A1", 42.0).expect("A1");
    ws.add_image(test_image(1, "Picture 1", 2, 3));

    let bytes = XlsWriter::write_to_bytes(&wb).expect("serialize");
    std::fs::create_dir_all(SHARED_DIR).expect("shared dir");
    let pid = std::process::id();
    let path = format!("{SHARED_DIR}/duke_picture_{pid}.xls");
    std::fs::write(&path, &bytes).expect("write");

    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .unwrap();
    let outcome: Result<f64, String> = rt.block_on(async {
        let mut bridge =
            duke_sheets_libreoffice::bridge::LibreOfficeBridge::connect("127.0.0.1", 2002)
                .await
                .map_err(|e| format!("connect: {e}"))?;
        let mut wb_in = bridge
            .open_workbook(&path)
            .await
            .map_err(|e| format!("open: {e}"))?;
        wb_in
            .get_cell_value("A1")
            .await
            .map_err(|e| format!("A1: {e}"))
    });
    let _ = std::fs::remove_file(&path);
    let a1 = outcome.expect("LO must open our XLS with picture without error");
    assert!(
        (a1 - 42.0).abs() < 1e-9,
        "A1 must round-trip; got {a1} (expected 42)"
    );
}

#[test]
fn empty_workbook_emits_no_blip_store() {
    // No images = no MSODRAWINGGROUP / MSODRAWING / BSTORE_CONTAINER
    // emission. Confirm by writing, parsing, and verifying the
    // workbook stream has zero drawing-group records.
    let mut wb = Workbook::new();
    wb.worksheet_mut(0)
        .unwrap()
        .set_cell_value("A1", "value")
        .expect("A1");

    let bytes = XlsWriter::write_to_bytes(&wb).expect("serialize");
    let parsed = XlsReader::read(Cursor::new(&bytes)).expect("read");
    assert_eq!(parsed.worksheet(0).unwrap().image_count(), 0);
}
