//! End-to-end tests for duke-sheets-xlsx.
//!
//! These tests use fixtures generated by PyUNO (LibreOffice's Python-UNO API)
//! to verify that our XLSX reader correctly handles files created by an
//! authoritative source.
//!
//! ## Test Strategy
//!
//! 1. **Reading Tests**: PyUNO generates XLSX fixtures with known content.
//!    Our tests read these fixtures and verify the content matches expectations.
//!
//! 2. **Writing Tests** (future): Our writer creates XLSX files, which are
//!    then verified by PyUNO to ensure compatibility.
//!
//! ## Running Tests
//!
//! ```bash
//! # Generate fixtures first (requires Docker)
//! mise run fixtures:generate
//!
//! # Run E2E tests
//! cargo test -p duke-sheets-xlsx --test e2e
//!
//! # Run with verbose output
//! cargo test -p duke-sheets-xlsx --test e2e -- --nocapture
//! ```
//!
//! ## Fixture Generation
//!
//! Fixtures are generated using the PyUNO framework in `tests/fixtures/pyuno/`.
//! See `tests/fixtures/pyuno/README.md` for details.

mod common;
mod reading;

// Re-export common utilities for submodules
pub use common::*;
